services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver_db
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: 'abc!123' 
    ports:
      - 1435:1435
    volumes:
      - sqlserver_data:/var/opt/mssql/data 

volumes:
  sqlserver_data: